# Generated by Django 4.1.6 on 2023-02-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
